language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
cache: pip
script:
 - nosetests --with-coverage
install:
 - pip install coverage
 - pip install codeclimate-test-reporter
 - pip install -r requirements.txt
